config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :jobs

  devise_for :users

 get '/help', to: 'pages#help', as: 'help_path'

 get '/applied_user/:job_id', to: 'jobs#applied_user', as: 'applied_user'
 delete '/cancel/:job_id', to: 'jobapplications#destroy', as:'cancel_path'
 
 post'/apply/:job_id', to: 'jobapplications#create', as: 'apply_path'
 get '/my_applied_jobs', to: 'jobapplications#my_applied_jobs', as: 'my_applied_jobs'
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.roles == "employer"
        can [:create], Job
        can [:read, :edit, :update, :delete], Job, user_id: user.id
      else
        can :manage, Jobapplication
        can :read, :all
      end
  
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :user
	has_many :jobapplications, dependent: :destroy
  validates_presence_of :user_id, :title, :description, :experience, :salary
end

app/models/jobapplication.rb
class Jobapplication < ApplicationRecord
	belongs_to :user
	belongs_to :job
	validates :user, uniqueness: { scope: :job,
    message: "you already applied" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :jobs
 	has_many :jobapplications
 validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create, message: "invalid format of email"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	rescue_from CanCan::AccessDenied do |exception|

  	redirect_to root_url, alert: exception.message
  end
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    jobs_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:roles])
  end
end

app/controllers/jobapplications_controller.rb
class JobapplicationsController < ApplicationController  
  def create
    @job =Job.find(params[:job_id])
    job_application = Jobapplication.new(job: @job, user: current_user, isapplied: true)

    authorize! :create, job_application

    if job_application.save
      UserMailer.welcome_email(@job).deliver_now
    end
  end     
      
  def destroy
    @job =Job.find(params[:job_id])
    job_application = Jobapplication.find_by(job_id: @job, user_id: current_user)

    authorize! :destroy, job_application

    if job_application.destroy
      flash[:notice] = "You cancel the job, good luck!"
    end
  end

   def my_applied_jobs
    authorize! :my_applied_jobs, Jobapplication
    @my_applied_jobs = Jobapplication.where(user: current_user)
   end 
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_job, only: %i[show edit update destroy]

  # GET /jobs
  def index
    if current_user.roles == "employer"
      _jobs = Job.where(:user_id => current_user.id)
    else
      _jobs = Job.all.order("created_at desc")
    end
    @jobs = _jobs.page(params[:page]).per(10)
  end

  # GET /jobs/1
  def show
    authorize! :read, @job
  end

  # GET /jobs/new
  def new
    @job = current_user.jobs.new
  end

  # GET /jobs/1/edit
  def edit
    authorize! :edit, @job
  end

  # POST /jobs
  def create
    @job = current_user.jobs.build(job_params)
    authorize! :create, @job
    @job.user_id = current_user.id

    if @job.save
      redirect_to @job, notice: "job create successfully"
    else
      render :new
    end
  end

  # PATCH/PUT /jobs/1
  def update
    authorize! :update, @job

    if @job.update(job_params)
      redirect_to @job
      flash[:notice] = "job updated successfully !"
    else
      render :edit
    end
  end

  # DELETE /jobs/1
  def destroy
    authorize! :delete, @job
    @job.destroy
    
    redirect_to jobs_url, notice: 'Job was successfully destroyed.'
  end

  def applied_user
     @job = Job.find(params[:job_id])
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
       @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :description, :salary, :experience)
    end
end
   

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end 
  
  def help
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apply_helper.rb
module ApplyHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/jobapplications/create.js.erb
$(".job-action-button-<%= @job.id %>").html("<%= escape_javascript(render 'jobs/job_cancel_button', job: @job ) %>");
alert('You have applied, good luck!');

app/views/jobapplications/destroy.js.erb
$(".job-action-button-<%= @job.id %>").html("<%= escape_javascript(render 'jobs/job_apply_button', job: @job ) %>");
alert('You have cancelled your application, good luck!')

app/views/jobapplications/my_applied_jobs.html.erb
<h3>your applied jobs</h3>
<b>Count   <%= @my_applied_jobs.count %></b>
 <% @my_applied_jobs.each do |jobs| %>
  <li><%= jobs.job.title %></li>
<% end %>

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:
      </h2>
      <ul>
        <% job.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <h4><%= form.label :title %></h4>
    <%= form.text_field :title %>
  </div>

  <div class="field">
   <h4><%= form.label :description %></h4>
    <%= form.text_area :description, required: true, input_html: { class: "textarea" } %>
  </div>

  <div class="field">
    <h4><%= form.label :salary %></h4>
    <%= form.number_field :salary %>
  </div>

  <div class="field">
    <h4><%= form.label :experience %></h4>
    <%= form.number_field :experience %>
   <%= form.select :experience_type, options_for_select([["Select One", ""], "Year", "Month"]), :class => 'genForm_dropBox' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script type="text/javascript">
  exp_interval = $('#job_experience').val()
  exp_interval_type = $('#job_experience_type').val()
    exp_interval_type.onchange = function() {
     $ (exp_interval.value) = $ (exp_interval_type.value);
}

</script>

app/views/jobs/_job_apply_button.html.erb
<%= link_to 'Apply ', apply_path_url(job), method: :post, class: "btn btn-default btn-sm",:remote => true %>

app/views/jobs/_job_cancel_button.html.erb
<%= link_to 'Cancel', cancel_path_url(job), method: :delete, data: { confirm: 'Are you sure?'}, :remote => true, class: "btn btn-default btn-sm"%>

app/views/jobs/applied_user.html.erb
<% @job.jobapplications.each do |a| %>
	<%= a.user.email %>
<% end %>

app/views/jobs/edit.html.erb
  <div class="container">
    <div class="columns">
      <div class="column is-8 is-offset-2">
        <h1 class="title is-3">Editing Job</h1>
        <%= render 'form', job: @job %>
      </div>
    </div>
  </div>

app/views/jobs/index.html.erb
<h1>Jobs</h1>
<%if can? :update, Job %>
<b><h3><%= link_to 'Create New Job', new_job_path%></b></h3>
<%end%>
<hr>
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $(".table tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
<b>Type something to search job:</b>
<input id="myInput" type="text" placeholder="Search..">
<div class="container">            
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Salary</th>
        <th>Experience</th>
        <%if can? :update, Job %>
          <th>Applied_users_count</th>
        <%end%>
        <th colspan="4"><center>Action</center></th>
      </tr>
    </thead>
   <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.description %></td>
        <td><%= job.salary %></td>
        <td><%= job.experience %></td>
        <%if can? :update, Job %>
          <td><%= job.jobapplications.count %></td>
          <td><%= link_to 'Show', job, class: "btn btn-default btn-sm"%></td>
          <td><%= link_to 'Edit', edit_job_path(job), class: "btn btn-default btn-sm" %></td>
          <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-default btn-sm"%></td>
          <td><%= link_to 'Applied Users', applied_user_path(job), class: "btn btn-default btn-sm"%></td>
        <%else%>
          <td>
            <div class="job-action-button-<%= job.id %>">
              <% if current_user.jobapplications.find_by(job: job).nil? %>
                <%= render 'job_apply_button', job: job %>
              <%else%>
                <%= render 'job_cancel_button', job: job %>
              <% end %>
            </div>
          </td>
        <%end%>
       </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @jobs %>
<br>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<h4><strong>Title:</strong>
  <%= @job.title %>
</p></h4>

<p>
  <h4><strong>Description:</strong>
  <%= @job.description %>
</p></h4>

<p>
  <h4><strong>Salary:</strong>
  <%= @job.salary %>
</p></h4>

<p>
  <h4><strong>Experience:</strong>
  <%= @job.experience %>
</p></h4>
<h4><%= link_to 'Back', jobs_path %></h4>

app/views/layouts/_footer.html.erb
<button type="button"
onclick="document.getElementById('demo').innerHTML = Date()">
Click me to display Date and Time.</button>

<p id="demo"></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% elsif alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <h4><%= link_to "Job Board", root_path, id: "logo", style:'color: #fff;' %></h4>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <% if current_user.roles == "employer" %> 
                <li><%= link_to 'Show your all Jobs', jobs_path, style:'color: #fff;' %></li>
              <% else %>
                <li><%= link_to 'Show all Jobs', jobs_path, style:'color: #fff;' %></li>
              <%end%>
              <%if can? :read, Jobapplication %>
                <li><%= link_to "My Applied Jobs", my_applied_jobs_path%></li>
              <% end %>
              <li><%= link_to "Sign Out", destroy_user_session_path, style:'color: #fff;', method: :delete %></li>
            <% else %>
              <li> <%= link_to "Sign in", new_user_session_path, style:'color: #fff;' %></li>
            <% end %>
            <li><%= link_to "Help",   help_path_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://www.railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Job Portal App</h1>
  <h2>
    This is the page for the
    <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    for job application.
  </h2>
</div>
<div>
<%= link_to image_tag("portal.jpeg", alt: "logo"),                       
            'http://rubyonrails.org/' %>
</div>

app/views/pages/portal.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Job Portal App</h1>
  <h2>
    This is the page for the
    <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    for job application.
  </h2>
</div>
<div>
<%= link_to image_tag("portal.jpeg", alt: "logo"),                       
            'http://rubyonrails.org/' %>
</div>